# 上下文初始化加载
info:
  name: lession-1-sms-interface
#端口
server:
  port: 9003

# 配置eureka
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    # eureka server地址
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/
  instance:
    # 心跳间隔
    # properties中配置：eureka.instance.leaseRenewalIntervalInSeconds
    leaseRenewalIntervalInSeconds: 30

# 这个配置会被spring.application.instance_id覆盖（默认 hostname，appnane，port）
#    metadataMap: 
#      instanceId: ${spring.application.name}:${spring.cloud.client.hostname}:${server.port}:${random.value}
